version: '3.8'
services:
  api:
    container_name: tinygrad-api-dev
    build: .
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
    volumes:
      - ./:/src
    labels:
      kompose.service.type: LoadBalancer
